### ISSUE TITLE
Is there any example on how to use this with FastAPI Backend?

### ISSUE THREAD

**Issue by AIAnytime** [ant-design/pro-chat#100]
Is there any example on how to use this with FastAPI Backend?

I have built an API using Langchain and FastAPI in Python and now wants to leverage Pro-chat with that. Is it possible?

**Comment by ONLY-yours** [comment]
ProChat doesn’t matter what backend and network framework you use, if api is http/https(sse or not donent matter), thats will be ok to use 

any way, ProChat is a React lib, so choose any react framework u like, such as NextJs

this is a demo: [Qwen-NextJs](https://github.com/ant-design/pro-chat/tree/main/demos/qwen-nextjs) hope it will help u

**Comment by iamvermajayant** [comment]
Can we stream the responses whose media type is application/json instead of text/event-stream ?

**Comment by ONLY-yours** [comment]
> Can we stream the responses whose media type is application/json instead of text/event-stream ?

if just text, thats will be fine

```ts
<ProChat
        request={async (messages) => {
          const text = "mock data"
          return new Response(text);
        }}
      />

```

and if u want show some special case, use chatItemRenderConfig render to render anything u like [demos](https://pro-chat.antdigital.dev/guide/servers-push#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F)
@iamvermajayant hope this work for u

**Comment by ONLY-yours** [comment]
i think this issue can be closed? hahaha
