### ISSUE TITLE
👑 [需求] 自定义错误消息

### ISSUE THREAD

**Issue by FrancisKong** [ant-design/pro-chat#102]
### 🥰 需求描述

当前 ProChat 无法自定义错误消息，对于 `request` 参数返回 response.ok 为 false 的响应，在界面上都是显示 `response error, status: ` ，这不太符合实际应用场景的需求。

### 🧐 解决方案

对于 response.ok 为 false 的响应，应当读取 body 里的内容作为错误信息展示，例如

```javascript
        <ProChat
          request={async (messages) => {
              return new Response("token 长度超限", { status: 500 })
          }
       </ProChat>
```

此时界面上应该展示的错误信息是 `token 长度超限` 

### 🚑 其他信息

无

**Comment by liguobao** [comment]
这个感觉很需要....
