### ISSUE TITLE
How to make proChat UI in English language instead of Chinese?

### ISSUE THREAD

**Issue by AIAnytime** [ant-design/pro-chat#107]
Currently the language is Chinese by default as shown in the image. But I want English Language by default

![image](https://github.com/ant-design/pro-chat/assets/30049737/c4b6532c-c8d0-4690-a6f8-416816f99963)

![image](https://github.com/ant-design/pro-chat/assets/30049737/00e95b15-15e3-4709-8688-43e179a67559)

**Comment by ONLY-yours** [comment]
nice question, we are doing the globalization things，links：https://github.com/ant-design/pro-chat/issues/56

**Comment by AIAnytime** [comment]
> nice question, we are doing the globalization things，links：#56

I have seen that but I couldn't make it work.. Can you please help the users of Prochat UI where to make the changes? which file or any documentation available?

**Comment by AIAnytime** [comment]
> nice question, we are doing the globalization things，links：#56

Hi Any help on this? Can you answer where to make changes for Globalization? We need English and not only Chinese.

**Comment by ONLY-yours** [comment]
> > nice question, we are doing the globalization things，links：#56
> 
> I have seen that but I couldn't make it work.. Can you please help the users of Prochat UI where to make the changes? which file or any documentation available?

we still doing this work, u can find the feature in pull request page, maybe it will be ready in next small version

**Comment by AIAnytime** [comment]
> > > nice question, we are doing the globalization things，links：#56
> > 
> > I have seen that but I couldn't make it work.. Can you please help the users of Prochat UI where to make the changes? which file or any documentation available?
> 
> we still doing this work, u can find the feature in pull request page, maybe it will be ready in next small version
> 
> @AIAnytime wating this pr ready haha
> https://github.com/ant-design/pro-chat/pull/106

Thanks for the reply. Any other alternative to Pro Chat? I loved the components but can't wait many days to get the solution up and running.

**Comment by AIAnytime** [comment]
Is Globalization PR is merged?

**Comment by ONLY-yours** [comment]
> Is Globalization PR is merged?

not ready hahaha plz wait a time  QAQ

**Comment by SadmanYasar** [comment]
Just want to add that we can set the locale prop in the ProChat component to en-US and it works.
