### ISSUE TITLE
Loader is still running after completion of output.

### ISSUE THREAD

**Issue by AIAnytime** [ant-design/pro-chat#109]
Hi, Loader is still running after completion of output. Can you please tell me how to fix it?

![image](https://github.com/ant-design/pro-chat/assets/30049737/95143842-49df-412c-83a3-28557e2b26ec)

**Comment by ONLY-yours** [comment]
> Hi, Loader is still running after completion of output. Can you please tell me how to fix it?


we use setTimeOut, thats cause this problem, we will fix it in this pr:

https://github.com/ant-design/pro-chat/pull/103

**Comment by ONLY-yours** [comment]
fixed by 1.10.1
