### ISSUE TITLE
👑 [需求] markdown插件支持

### ISSUE THREAD

**Issue by sivdead** [ant-design/pro-chat#114]
### 🥰 需求描述

希望能支持markdown插件,我看到Pro-editor使用的markdown组件本身是支持的,希望能作为参数提供出来

### 🧐 解决方案

![image](https://github.com/ant-design/pro-chat/assets/27731043/50cfd3f9-e240-4d9e-925a-8f1954c48f81)

**Comment by ONLY-yours** [comment]
是的，之前口子一直都开好了，但是没来急的做这个需求，你愿意给我们来一个 pr么？

**Comment by sivdead** [comment]
> 是的，之前口子一直都开好了，但是没来急的做这个需求，你愿意给我们来一个 pr么？

可以的

**Comment by sivdead** [comment]
#116 解决了,现在可以直接传两个markdown插件参数进来了
