### ISSUE TITLE
🐛[BUG] 服务侧SSE返回，对话显示延迟，1.10.1引入

### ISSUE THREAD

**Issue by liguobao** [ant-design/pro-chat#119]
![WechatIMG7017](https://github.com/ant-design/pro-chat/assets/10910802/652017ef-c4b2-4ce4-9dd8-34d2c8818872)

如图，此次对话 HTTP SSE请求大概是5.1s，显示已经接受完成所有数据，同时回复也正常停止了。

但是页面中机器人状态依旧是“回复中”，输入框禁用，

服务端日志显示此次请求为5085.7301ms，可以映证SSE请求正常完成。

[2024-03-09 14:57:53.590 | INF | 0HN20937RBC7K:00000002 | Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker] 
Executed Controllers.ProxyOpenAIController.Openai   in 5085.7301ms

代码没什么特别处理。

```js
      <ProChat
        style={{ height: '500px' }}
        chats={cachedChats}
        request={async (messages: any) => {
          let messageRep = {
            model: currentRow.model,
            messages: [...messages] as any,
            stream: true,
          }
          const response: any = await openai.chat.completions.create(messageRep);
          const stream = OpenAIStream(response);
          return new StreamingTextResponse(stream);
        }}
      ></ProChat>
```

**Comment by liguobao** [comment]
https://github.com/ant-design/pro-chat/issues/109

我看这个Issue已经关闭了，但是好像出现了新的问题。
1、对话延迟显示
2、对话不会自动下拉到最后了。

**Comment by ONLY-yours** [comment]
@liguobao 试试？发了 1.10.2

**Comment by liguobao** [comment]
> @liguobao 试试？发了 1.10.2

在1.10.2里面，打字机效果恢复了，但是Loading 又变成了请求结束之后好一会才停止。
我看上个版本的修复代码是超时导致的，这个有什么比较舒服的解决方案吗？

**Comment by ONLY-yours** [comment]
> > @liguobao 试试？发了 1.10.2
> 
> 在1.10.2里面，打字机效果恢复了，但是Loading 又变成了请求结束之后好一会才停止。 我看上个版本的修复代码是超时导致的，这个有什么比较舒服的解决方案吗？ [32e6347](https://github.com/ant-design/pro-chat/commit/32e63473c92c6902a9c633ced4d4f6de7ed24a0f)
> 
> 照着这个Commit来说，还是只能在超时之后终止Loading
> 
> @ONLY-yours

「但是Loading 又变成了请求结束之后好一会才停止」这个我在使用 chatgpt 的时候没复现，会迟一点是因为 SSE 结束的时候，打字机可能还没走完，会有剩余的文字还在缓冲流里面，可以看下代码，有一个 output 的队列在维护，等队列彻底结束才算是 Loading 结束。

**Comment by ONLY-yours** [comment]
关于超时的，目前除非主动断开链接，或者返回 error 的 respone 外，sse 是不会主动断开的，手动停止 loading 是比较正确的做法。

如果一定要做类似的逻辑，可以采用 useProChat hooks 里面的 stopGeretae 来停止生成该内容

**Comment by liguobao** [comment]
我这边使用了中转代理和自己实现的SSE，都复现了这个问题，
如果是直接非Stream返回应该是看不到这个的。

**Comment by liguobao** [comment]
> 关于超时的，目前除非主动断开链接，或者返回 error 的 respone 外，sse 是不会主动断开的，手动停止 loading 是比较正确的做法。
> 
> 如果一定要做类似的逻辑，可以采用 useProChat hooks 里面的 stopGeretae 来停止生成该内容

我看到SSE是有终止的消息的，直接就是stop的呀。

**Comment by ONLY-yours** [comment]
> > 关于超时的，目前除非主动断开链接，或者返回 error 的 respone 外，sse 是不会主动断开的，手动停止 loading 是比较正确的做法。
> > 如果一定要做类似的逻辑，可以采用 useProChat hooks 里面的 stopGeretae 来停止生成该内容
> 
> 我看到SSE是有终止的消息的，直接就是stop的呀。

对的，这个逻辑我们支持的，你是说默认 SSE 返回结束的标志的时候还是 Loading 态么？我这边这个 Case 是对的

**Comment by liguobao** [comment]
<img width="1113" alt="截屏2024-03-11 13 04 14" src="https://github.com/ant-design/pro-chat/assets/10910802/a4e5e861-9f10-4786-84bc-531fd41beac6">
<img width="1393" alt="截屏2024-03-11 13 05 06" src="https://github.com/ant-design/pro-chat/assets/10910802/71689ba3-a4ad-44cb-b7ea-d363eff32740">
就图二来说，完整的请求在11s左右完成了，但是机器人的Loading和数据库发送状态一直都是Loading.

**Comment by liguobao** [comment]
> > > 关于超时的，目前除非主动断开链接，或者返回 error 的 respone 外，sse 是不会主动断开的，手动停止 loading 是比较正确的做法。
> > > 如果一定要做类似的逻辑，可以采用 useProChat hooks 里面的 stopGeretae 来停止生成该内容
> > 
> > 
> > 我看到SSE是有终止的消息的，直接就是stop的呀。
> 
> 对的，这个逻辑我们支持的，你是说默认 SSE 返回结束的标志的时候还是 Loading 态么？我这边这个 Case 是对的

大佬你要不用一下我这边的接口测试一下？我给你个权限看看。

**Comment by ONLY-yours** [comment]
> > > > 关于超时的，目前除非主动断开链接，或者返回 error 的 respone 外，sse 是不会主动断开的，手动停止 loading 是比较正确的做法。
> > > > 如果一定要做类似的逻辑，可以采用 useProChat hooks 里面的 stopGeretae 来停止生成该内容
> > > 
> > > 
> > > 我看到SSE是有终止的消息的，直接就是stop的呀。
> > 
> > 
> > 对的，这个逻辑我们支持的，你是说默认 SSE 返回结束的标志的时候还是 Loading 态么？我这边这个 Case 是对的
> 
> 大佬你要不用一下我这边的接口测试一下？我给你个权限看看。

不用，我拿 ChatGPT 再试试看

**Comment by ONLY-yours** [comment]
依然无法复现你说的问题，用的是 ChatGPT 的接口：

![image](https://github.com/ant-design/pro-chat/assets/52664827/9c82fa56-bd74-44e5-9ecd-38145ee8241a)

虽然接口是 9.26s 就结束了，但是上面说的缓动输出，实际上大概是 10s 左右彻底输出完毕。

查看下你这个 SSE 最后返回这个 Done 结束符了么

![image](https://github.com/ant-design/pro-chat/assets/52664827/6323d44e-d37b-4073-9b8e-4472c12f60dc)

**Comment by liguobao** [comment]
好，我再看下，我可能知道是为嘛了，感觉我这边和中转实现的SSE也不太一样？
我在浏览器控制台是没看到SSE的数据包的，在PostMan能看到

**Comment by liguobao** [comment]
最终确认，升级到1.10.2 问题修复，感恩大佬~
