### ISSUE TITLE
🐛[BUG]输入框输入多行信息，发送之后输入框位置没有及时下移

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#122]
### 🐛 bug 描述

输入框输入多行信息，信息发送之后输入框位置停留在上方，没有及时下移

### 📷 复现步骤
输入框多行输入
![image](https://github.com/ant-design/pro-chat/assets/75489410/fa98aa9e-f609-4fa5-96c9-f341ac5b180c)
发送信息之后 输入框位置没有及时下移
![image](https://github.com/ant-design/pro-chat/assets/75489410/043f9c42-8606-4350-8727-095c8a669da8)

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ONLY-yours** [comment]
我在浏览器上模拟的时候没出现这个问题，是手机端才会触发么

**Comment by Tss-16** [comment]
> 我在浏览器上模拟的时候没出现这个问题，是手机端才会触发么

好像是的 :(

**Comment by ONLY-yours** [comment]
> > 我在浏览器上模拟的时候没出现这个问题，是手机端才会触发么
> 
> 好像是的 :(

估计是一些 css 问题，我看看怎么在 mobile 上兼容下

**Comment by Tss-16** [comment]
> 
> 估计是一些 css 问题，我看看怎么在 mobile 上兼容下

好的

**Comment by Tss-16** [comment]
感谢最终调试`.ant-pro-chat-chat-list-container{
        flex:1
      }`解决聊天框样式问题
