### ISSUE TITLE
🐛[BUG] 代码块中，无法正常显示 html 代码

### ISSUE THREAD

**Issue by yangfuhai** [ant-design/pro-chat#127]
### 🐛 bug 描述

让 ai 写一段 html 的 hello world， ai 返回的 html 内容如下时， html 代码块显示不正确：

在HTML中编写一个“Hello World”非常简单，以下是一个基本的例子：

```html
<!DOCTYPE html>
<html>
<head>
    <title>Hello World Page</title>
</head>
<body>

<h1>Hello World!</h1>

</body>
</html>
```

这段代码将在浏览器中显示一个标题为“Hello World!”的网页。`<!DOCTYPE html>`声明告诉浏览器这是一个HTML5文档，`<html>`标签定义了整个HTML文档的开始和结束。`<head>`标签包含了文档的元数据，比如标题，而`<body>`标签内包含的是网页的所有可见内容。在这个例子中，`<h1>`标签表示一个一级标题，其中包含了文本“Hello World!”。

### 📷 复现步骤

让 ai 返回一段 html 代码即可复现。

### 🏞 期望结果

能够正常渲染 html 代码块

### 💻 复现代码

无

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

以下是错误渲染的截图：

![image](https://github.com/ant-design/pro-chat/assets/1539806/39dfdf19-42dd-4f68-9eea-6d08a1e73a2e)

**Comment by ONLY-yours** [comment]
@rdmclin2 看起来是直接用的 pro-editor，看看这个

**Comment by rdmclin2** [comment]
目测是 Markdown 自动解析了 html 代码展示，我这边切换语言就可以看到代码，我瞧瞧。

**Comment by carmanchang** [comment]
遇到同样问题，pro-editor看官网上例子展示html代码是正常的，pro-chat里不正常

**Comment by ONLY-yours** [comment]
> 遇到同样问题，pro-editor看官网上例子展示html代码是正常的，pro-chat里不正常

@carmanchang  我看 proEditor 还没发版本，修好了官网以及上去了

![image](https://github.com/ant-design/pro-chat/assets/52664827/12a18e12-1402-4f74-9f7c-4ab127788e89)

@rdmclin2 帮忙 Editor 发个 fix
