### ISSUE TITLE
🐛[BUG] 在使用 DraggablePanel 的情况下，弹出菜单的层级不正确

### ISSUE THREAD

**Issue by yangfuhai** [ant-design/pro-chat#128]
### 🐛 bug 描述

如下图所示，在使用 DraggablePanel 的情况下，点击消息菜单弹出的层级不正确。

![image](https://github.com/ant-design/pro-chat/assets/1539806/aac0dc67-3653-4a34-be18-5218977bab9e)

### 🏞 期望结果

能够正确弹出菜单。

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.10.3]
- 浏览器环境 chrome 121.0.6167.85
- 开发环境 [mac OS]

**Comment by yangfuhai** [comment]
![image](https://github.com/ant-design/pro-chat/assets/1539806/336d6a7d-f380-4df0-971b-81a5119918a1)

不建议使用 DraggablePanel 了，配合 antd 的 modal + react-draggable 更顺滑。

**Comment by ONLY-yours** [comment]
> ![image](https://private-user-images.githubusercontent.com/1539806/317590351-336d6a7d-f380-4df0-971b-81a5119918a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDA2NjUsIm5iZiI6MTcxMTYwMDM2NSwicGF0aCI6Ii8xNTM5ODA2LzMxNzU5MDM1MS0zMzZkNmE3ZC1mMzgwLTRkZjAtOTcxYi04MWE1MTE5OTE4YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDQzMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJkZmQwOTlmMDIzYTdjZDZiOWY3NDc4YmE4Njg2MDgwY2VkZjk4MDlhYzA5MjhjZTczMzhmYjc1YjkzNjRkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._1wAGoTYRcETunnQyTmcv0NkxVB6vzJ7amowLw9l9HY)
> 
> 不建议使用 DraggablePanel 了，配合 antd 的 modal + react-draggable 更顺滑。

我后面改成用 antd 的例子好了 thanks
