### ISSUE TITLE
🐛[BUG] 移动端真机下发送消息一直在转圈圈

### ISSUE THREAD

**Issue by RainyLiao** [ant-design/pro-chat#130]
### 🐛 bug 描述

![image](https://github.com/ant-design/pro-chat/assets/90637572/1c1cf698-b2b1-476c-9a0c-fb771ca7f9a1)

### 📷 复现步骤

在真机部署的H5容器环境下，一直是loading的状态，即使返回固定的new Response纯字符串对象，官网随便一个demo皆可。如果用网页端生成二维码放至app内的容器中运行是正常的，得部署至真机。而且如果添加了antd关于css where属性的降级provider，会导致样式错乱了。
### 🏞 期望结果
正常响应请求，不是loading的状态。

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.9.3]
- 浏览器环境 真机windwane
- 开发环境 [mac OS]

**Comment by RainyLiao** [comment]
<img width="453" alt="image" src="https://github.com/ant-design/pro-chat/assets/90637572/5d0cea7d-0066-4661-bcd9-fd12e7f75839">
pro-chat/src/ProChat/utils/fetch.ts
const { value, done: doneReading } = await reader.read();
模拟了代码，通过Vconsole抓取，觉得是解析Response对象的时候会产生value为空的情况，导致decoder.decode报错

**Comment by ONLY-yours** [comment]
「得部署至真机」展开说说？是直接手机浏览器 H5 打开？还是使用一些 Hybrid 的方案？

「属性降级」这个也麻烦展开说说？

**Comment by RainyLiao** [comment]
> 「得部署至真机」展开说说？是直接手机浏览器 H5 打开？还是使用一些 Hybrid 的方案？
> 
> 「属性降级」这个也麻烦展开说说？

安卓app内的webview容器，我把pro-chat内部的fetchSSE方法的处理在onRequest上写了一遍，直接H5打开的话，while循环中使用decoder.decode(value, { stream: !doneReading })的时候，是可以的，最简单的形式就是在控制台输出。
<img width="345" alt="image" src="https://github.com/ant-design/pro-chat/assets/90637572/8be75b8a-e1a4-47d1-90e1-97a640589452">

属性降级我是参考antd官方文档配置的，因为在移动端使用还是对H5的css兼容性有些要求，大量使用的where语法，兼容性比较差：
https://ant-design.antgroup.com/docs/react/compatible-style-cn

**Comment by RainyLiao** [comment]
测了下应该是兼容性问题导致的，在ios下，Response对象没有body属性。在安卓下，在解码无效数据时 [TextDecoder.decode() ](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder)方法抛出了 TypeError。想着如果不使用流式输出，是不是可以在request请求方法中接收固定的Promise<string>返回就可以了？

**Comment by arvinxx** [comment]
> 是不是可以在request请求方法中接收固定的Promise返回就可以了

理论上来说是的

**Comment by RainyLiao** [comment]
排查后以上bug是在内部Hybrid 下的问题（和prochat无关），纠正后的问题总结：
1. 支持非流式请求，返回`Promise<string>`，而不是`Promise<Response>`
2. 支持通过and StyleProvider 降级where选择器
