### ISSUE TITLE
🐛[BUG] 在输入框中输入有换行的内容时，在对话框里会显示成一行

### ISSUE THREAD

**Issue by misakayao** [ant-design/pro-chat#138]
### 🐛 bug 描述

在输入框中输入有换行的内容时，在对话框里会显示成一行。问题原因应该是在html中\n起不到换行的作用，需要做预处理将\n转换为br

### 📷 复现步骤

在输入框中输入有换行的内容

![image](https://github.com/ant-design/pro-chat/assets/10098771/944abdb3-76d0-4912-ab4f-670368017277)

![image](https://github.com/ant-design/pro-chat/assets/10098771/4556ed52-2ed5-487a-9f59-f0ee852e7e81)

![image](https://github.com/ant-design/pro-chat/assets/10098771/4eae60c0-e90b-4786-b26f-1d7bed343bc9)

### 🏞 期望结果

在对话框里显示和输入框中一致的内容，或者可以考虑提供预处理

### © 版本信息

- @ant-design/pro-chat 版本: 1.11.0

**Comment by ONLY-yours** [comment]
@rdmclin2 感觉还是 markdown 一些奇怪的问题一起看看？

**Comment by misakayao** [comment]
您的邮件我已收到，感谢您的来信！

**Comment by ONLY-yours** [comment]
fixed ，更新版本即可
