### ISSUE TITLE
🧐[问题]使用setChats自定义推送消息无法实现auto scroll效果吗？

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#140]
### 🧐 问题描述

需要使用setChats自定义推送一些消息，消息到达底部无法实现自动滚动到最底部效果，只能手动滚动？

**Comment by ONLY-yours** [comment]
有些时候，推送消息并不一定要滚动到最下方，所以这个逻辑我们交给了用户自己来决定，有一个 scrollToBottom 的 ref 可以手动滚动

**Comment by ONLY-yours** [comment]
比较好的解决办法是，推送完成后，弹出一个 antd 的 message，提示用户有新消息，click 后调用下 scrollToBottom 到最新的内容
> scrollToBottom 的是同步的，所以可能会出现你 setChats 结束后，最新消息还没渲染完，scrollToBottom 计算的高度会有偏差，建议 setTimeOut 下然后 scrollToBottom

**Comment by Tss-16** [comment]
Prochat设置了`chatRef`属性，最终用`proChatRef.current.scrollToBottom()`完美解决！
