### ISSUE TITLE
👑 [需求] request属性里response是否有暴露的消息响应api?

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#141]
### 🥰 需求描述

用户发送消息触发request里的response输出流，消息输出时Input输入框一直处于loading状态，如果自定义input也想实现loading效果，有没有api可以获取消息响应是否结束来自定义输入框的button loading状态？

**Comment by realzbc** [comment]
useProChat---->getChatLoadingId

**Comment by Tss-16** [comment]
> useProChat---->getChatLoadingId

使用 useProChat会报错 Error: Seems like you have not used zustand provider as an ancestor.
![image](https://github.com/ant-design/pro-chat/assets/75489410/f7f10c3d-9bf5-4c45-8e96-58600698bf37)

**Comment by ONLY-yours** [comment]
包裹一下 ProChatProvider

**Comment by Tss-16** [comment]
> 包裹一下 ProChatProvider

包裹在最外层了，而且除了request属性 别的属性全部迁移到ProChatProvider里面了:[

**Comment by ONLY-yours** [comment]
> > 包裹一下 ProChatProvider
> 
> 包裹在最外层了，而且除了request属性 别的属性全部迁移到ProChatProvider里面了:[

不要放在同级哦，放到子级就好啦。下面这样子会报错

```ts
    const proChat = useProChat();
    <ProChatProvider initialChats={example.chats}>
      <ProChat />
    </ProChatProvider>

```

这样子可以成功


```ts

const Chat = ()=>{
    const proChat = useProChat();
   return <ProChat/>

}

    <ProChatProvider initialChats={example.chats}>
      <Chat />
    </ProChatProvider>

```

**Comment by Tss-16** [comment]
> 是因为在使用 useProChat 的时候，当前的 ProChatProvider 没挂载完全，而且也是找外层的，不会找内层的

！成功了！感谢！ 但是这个返回的ID怎么判断他是loading中还是已经加载结束了啊？==

**Comment by ONLY-yours** [comment]
> > 是因为在使用 useProChat 的时候，当前的 ProChatProvider 没挂载完全，而且也是找外层的，不会找内层的
> 
> ！成功了！感谢！ 但是这个返回的ID怎么判断他是loading中还是已经加载结束了啊？==

有返回就是还在 Loading，返回为 undefined 就是结束了
