### ISSUE TITLE
代码块展示切换主题色

### ISSUE THREAD

**Issue by carmanchang** [ant-design/pro-chat#143]
### 🧐 问题描述

代码块现在都是统一亮色吗，这块可以切换成黑色主题色吗，看pro-editor上是支持的
![Uploading image.png…]()

**Comment by ONLY-yours** [comment]
@carmanchang 

我有写暗黑模式的案例，看看这里
想要单独对代码块改动颜色的感觉不是很合理，全局切换可以这么做

https://pro-chat.antdigital.dev/guide/styles#%E4%B8%BB%E9%A2%98%E5%AE%9A%E5%88%B6

**Comment by carmanchang** [comment]
@ONLY-yours 请问有单独对代码块改动颜色吗？我们的UI就是这样设计的，突出代码块功能

**Comment by ONLY-yours** [comment]
> @ONLY-yours 请问有单独对代码块改动颜色的办法吗？我们的UI就是这样设计的，突出代码块功能

@carmanchang markdownProps 在文档里面藏的比较深，这个支持你透传 props 给 ProEditor 的 markdown 属性

**Comment by carmanchang** [comment]
@ONLY-yours 
![image](https://github.com/ant-design/pro-chat/assets/8892024/44d4dda7-32c1-421e-8f02-4bc944169006)
markdwonProps好像也设置不了

**Comment by ONLY-yours** [comment]
个人感觉不太方便了，建议自己用 chatItemRender 里面的 content 内容渲染了，或者包裹下 div 用 className 去覆盖
