### ISSUE TITLE
🐛[BUG] inputAreaProps不支持maxLength透传？

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#146]
### 🐛 bug 描述

组件传入inputAreaProps的maxLength属性 控制台报错且限制无效

### 📷 复现步骤

`inputAreaProps={{ maxLength: 5 }}`
![image](https://github.com/ant-design/pro-chat/assets/75489410/7894b5b9-d46b-4e6b-8b3b-14b1811d54f8)

### © 版本信息

- @ant-design/pro-chat 版本: [1.12.1]
- 浏览器环境[Chrome]
- 开发环境 [Windows]

**Comment by ONLY-yours** [comment]
@Tss-16 因为 inputArea 是由一个 AutoComplete 包裹 Input TextArea 实现的，会受控于顶部的 AutoComplete

这么写就行

```js
        inputAreaProps={{
          autoCompleteProps:{
            maxLength: 5,
          }
        }}

```

**Comment by Tss-16** [comment]
> @Tss-16 因为 inputArea 是由一个 AutoComplete 包裹 Input TextArea 实现的，会受控于顶部的 AutoComplete
> 
> 这么写就行
> 
> ```js
>         inputAreaProps={{
>           autoCompleteProps:{
>             maxLength: 5,
>           }
>         }}
> ```
原来如此！感谢
