### ISSUE TITLE
🧐[问题]markdown链接跳转是否支持新页面打开链接？

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#147]
### 🧐 问题描述

文本支持markdown语法可以实现 `[github](https://github.com/)` 点击跳转的效果，
但想要在新页面打开跳转页面好像无法解析？`[github](https://github.com/){:target="_blank"}`

**Comment by ONLY-yours** [comment]
这并不是一个标准的 markdown 语法吧。

我们支持 Markdown props 透传，去看看 React Markdown 的 参数，说不定有你想要的口子

**Comment by XlousZ** [comment]
可以问下后面是怎么解决markdown链接新页面跳转的么？

**Comment by Tss-16** [comment]
> 可以问下后面是怎么解决markdown链接新页面跳转的么？

`
 markdownProps={{
              rehypePlugins: [
                [
                  rehypeExternalLinks,
                  {
                    target: '_blank',
                    rel: ['nofollow', 'noopener', 'noreferrer'],
                  },
                ],
              ],
            }}
`
