### ISSUE TITLE
🐛[BUG] Dumi 主题 demo Tag 展示样式问题

### ISSUE THREAD

**Issue by SanGuiChen** [ant-design/pro-chat#150]
### 🐛 bug 描述

看起来「流式请求」那个部分应该是渲染出错了。
![image](https://github.com/ant-design/pro-chat/assets/77064828/9545d168-0768-44dd-802c-d86f0ae18b75)

### 📷 复现步骤
https://pro-chat.antdigital.dev/components/pro-chat#prochat-demo-request

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by ONLY-yours** [comment]
算是我们用的 dumi 主题的一个小问题
