### ISSUE TITLE
🧐[问题] 用fetchEventSource流式输出文字 没效果

### ISSUE THREAD

**Issue by Edward6463** [ant-design/pro-chat#152]
### 🧐 问题描述
使用fetchEventSource 在onmessage中逐字输出文字 prochat反应还是在loading 控制台已经可以实现逐字输出了，好像走了非流式

### 💻 示例代码

                         <ProChat
                            className={CustomClassName}
                            chatRef={proChatRef}
                            inputAreaRender={inputAreaRender}
                            userMeta={{ avatar: require(`@/assets/images/indexAvater.png`), placement: "left" }}
                            assistantMeta={{ avatar: require(`@/assets/images/ailist_bg1.png`) }}
                            chats={history}
                            style={{ height: '86vh' }}
                            chatItemRenderConfig={{
                                contentRender: (_, defaultContent) => {
                                    console.log(_)
                                    console.log(defaultContent)
                                    let { _primary } = _
                                    return (
                                        <div className={_.primary ? (styles.chatListUser2 + ' usertheme') : styles.chatListSty2}>
                                            {defaultContent}
                                        </div>
                                    );
                                },
                                actionsRender: false
                            }}
                            request={async (messages: { content: any; }[]) => {
                                console.log('messages', messages)
                                let sendlastmsg = messages[messages.length - 1].content
                                const url = 'aiSession/chat/';
                                let messagesstr = ''
                                await fetchEventSource(url + sessionId, {
                                    method: 'POST',
                                    headers: {
                                        Accept: 'text/event-stream',
                                        "Content-Type": "application/json", 
                                    },
                                    signal: ctrlAbout.signal,
                                    mode: 'cors',
                                    openWhenHidden: true,
                                    credentials: 'include',
                                    body: JSON.stringify({
                                        modeId: modeltype, newSession, msgType: 'text', content: sendlastmsg, sessionType: 'text',
                                    }),
                                    async onopen(response) {
                                        console.log('建立连接', response)

                                    },
                                    onmessage(ev) {
                                        console.log('接受消息', ev)
                                        console.log(this)
                                        messagesstr += ev.data
                                    },
                                    onclose() {
                                        console.log('关闭')
                                        ctrlAbout.abort();//出错后不要重试
                                        close();
                                    },
                                })
                                // const mockedData: string = `这是一段模拟的对话数据。本次会话传入了${messages.length}条消息`;
                                return new Response(messagesstr);
                            }}
                        />

### 🚑 其他信息
![image](https://github.com/ant-design/pro-chat/assets/22739469/17ca5bbe-a4ad-4958-8164-e945682b60ad)

**Comment by ONLY-yours** [comment]
关于 signal  控制的话，request 第三个参数就是我们透出的 signal，可以用我们的 signal来控制。

**Comment by ONLY-yours** [comment]
关于流式输出，可以看看我们的 demo：

https://pro-chat.antdigital.dev/guide/chatgpt

**Comment by lunar9621** [comment]
楼主 所以这个能用fetchEventSource吗

**Comment by ONLY-yours** [comment]
> 楼主 所以这个能用fetchEventSource吗

可以，只要是标准的就行，chatgpt 那样子的流返回就ok啦

**Comment by lunar9621** [comment]
好的 谢谢
