### ISSUE TITLE
🧐[问题] 官网的组件效果 是哪个版本？

### ISSUE THREAD

**Issue by millievn** [ant-design/pro-chat#156]
### 🧐 问题描述

我使用以下版本，和官网的交互效果差别很大。请问官网组件效果，是哪个版本的 pro-chat？
```
 "@ant-design/pro-chat": "^1.12.2",  
"@ant-design/pro-chat": "^2.0.4",  
```

https://pro-chat.antdigital.dev/components/pro-chat#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BE%93%E5%85%A5%E5%8C%BA%E5%9F%9F

### 🚑 其他信息

<img width="1408" alt="image" src="https://github.com/ant-design/pro-chat/assets/37304367/ab7ddf8d-5042-46f3-971e-dc93fb12cf7f">

**Comment by ONLY-yours** [comment]
用的是 1.x 版本哈 ，2.0 还在准备中，这个 Pr 彻底做好了才会合并进入主分支：

https://github.com/ant-design/pro-chat/pull/144
