### ISSUE TITLE
🐛[BUG]1.12.2 版本，设置了userMeta={{avatar:'/u_avatar.svg',title:"VIP顾客"}},但对话头像上方不展示别名

### ISSUE THREAD

**Issue by BarronLin** [ant-design/pro-chat#163]
### 🐛 bug 描述
1.12.2 版本，设置了userMeta={{avatar:'/u_avatar.svg',title:"VIP顾客"}},但对话头像上方不展示别名

### 📷 复现步骤

设置userMeta={{avatar:'/u_avatar.svg',title:"VIP顾客"}}

### 💻 复现代码

      <ProChat
        request={'http://localhost:8086/chat/stream'}
        config={{
            model:"ERNIE-Speed-8K",
            params:{
                user:"user-123456"
            }
        }}
        helloMessage={
          '欢迎使用 ProChat ，我是你的专属机器人，这是我们的 Github：[ProChat](https://github.com/ant-design/pro-chat)'
        }
        userMeta={{avatar:'/u_avatar.svg',title:"VIP顾客"}}
        assistantMeta={{ avatar: '/logo.svg', title: '小A客服' }}
        inputAreaProps={{
            autoCompleteProps: {
              placement: 'topRight',
            },
        }}
      />

### © 版本信息

- @ant-design/pro-chat 版本: 1.12.2
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息

<img width="389" alt="image" src="https://github.com/ant-design/pro-chat/assets/9267731/a6625e0c-efab-4b5d-86cd-e6a6d8d6f3be">

**Comment by ONLY-yours** [comment]
@BarronLin 需要你手动加入 showTitle 参数

现在默认 Title 是不主动展示的

**Comment by BarronLin** [comment]
😯是的，看到了 要 加showTitle

**Comment by zhanyeye** [comment]
加在这里，方便后来人

![image](https://github.com/user-attachments/assets/0f28b2cf-c75d-402e-8bea-eca60dc9df69)
