### ISSUE TITLE
🧐 antd 样式覆盖问题

### ISSUE THREAD

**Issue by miffy-w** [ant-design/pro-chat#169]
### 🚑 其他信息

<img width="667" alt="image" src="https://github.com/ant-design/pro-chat/assets/38873040/51d37223-46d9-45d8-b7d8-860d93ecc43d">

**Comment by ONLY-yours** [comment]
是当初设计的缺陷了，我看看怎么修复，有什么好的 idea 么？

**Comment by miffy-w** [comment]
> 是当初设计的缺陷了，我看看怎么修复，有什么好的 idea 么？

1、用 antd 中的 ConfigProvider 组件传 token 的方式修改样式是否可行？
2、不用太关注UI，让用户自定义，可能用户的项目中使用了 antd，使用宿主环境的样式

**Comment by ONLY-yours** [comment]
方案一二都是不错的选择，我们考虑下。

**Comment by miffy-w** [comment]
> 亲测使用 ConfigProvider 自定义前缀就可以暂时避免冲突，官方也可以设置一个默认的独立前缀和别的项目隔离

目前我这里就是这么解决的。
