### ISSUE TITLE
pro-chat如何接入reactjs

### ISSUE THREAD

**Issue by Sunshine-Zanilia** [ant-design/pro-chat#170]
pro-chat除了支持nextjs还支持reactjs吗？
我在react项目中如何集成pro-chat呢？
pro-chat对依赖版本也有要求吧。

**Comment by ONLY-yours** [comment]
支持的，只要是 React 框架基本都支持

如果使用默认的 Create-React-App 脚手架的话，只需要配置一些简单的 Webpack-Loader 就行的

版本依赖的话

react > 18 
antd > 5

只有这两个有要求呢

**Comment by uniquejava** [comment]
我就是在 vite5 + react18 项目中用的, 并不比 使用 Ant design 的 Button 麻烦, 直接包含 ProChat 组件就好使, no brainer, 码就完事
