### ISSUE TITLE
🧐[问题]stream模式下内容显示自动换行并且部分‘data: ’没有被替换

### ISSUE THREAD

**Issue by wangzi1204** [ant-design/pro-chat#172]
### 🧐 问题描述

stream模式下内容显示自动换行并且有部分‘data: ’没有被替换

### 💻 示例代码

                        const response = await fetch('/conversation', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json;charset=UTF-8',
                            },
                            body: JSON.stringify({messages: messages}),
                        });
                        const reader = response.body.getReader();
                        const decoder = new TextDecoder('utf-8');
                        const encoder = new TextEncoder();

                        const readableStream = new ReadableStream({
                            async start(controller) {
                                function push() {
                                    reader
                                        .read()
                                        .then(({done, value}) => {
                                            if (done) {
                                                controller.close();
                                                return;
                                            }
                                            const message = decoder.decode(value, {stream: true}).replace('data: ', '');
                                            controller.enqueue(encoder.encode(message));
                                            push();
                                        })
                                        .catch((err) => {
                                            console.error('读取流中的数据时发生错误', err);
                                            controller.error(err);
                                        });
                                }

                                push();
                            },
                        });
                        return new Response(readableStream);

### 🚑 其他信息
<img width="461" alt="截屏2024-04-22 16 03 23" src="https://github.com/ant-design/pro-chat/assets/42059256/1302dcae-3532-437f-9d6a-ee212b7c1b9d">

### 版本信息
@ant-design/pro-chat 版本: [1.12.2]
浏览器环境 [谷歌浏览器]
开发环境 [mac OS]

**Comment by ONLY-yours** [comment]
还是 reader 解析器的问题，如果你用的是 chatgpt 的话，可以直接用三方解析库：

详细可见该文：

https://pro-chat.antdigital.dev/guide/sse

**Comment by wangzi1204** [comment]
> 还是 reader 解析器的问题，如果你用的是 chatgpt 的话，可以直接用三方解析库：
> 
> 详细可见该文：
> 
> https://pro-chat.antdigital.dev/guide/sse

不是使用的chatgpt，后台函数中返回的就是文本内容，并根据这个demo 改写了reader。

**Comment by wangzi1204** [comment]
> 感觉需要根据这里的 chunk 做你的特殊业务逻辑了
> 
> ```js
> const message = decoder.decode(value, {stream: true}).replace('data: ', '');
> ```
> 
> 尝试打印下这个 message 然后决定看看 怎么 replace 之类的处理呢

我更改了一下后台函数，从SSE Response改为了stream Response，规避了replace的问题。

**Comment by uniquejava** [comment]
我和你的问题一模一样, 我后台用的 spring boot/ spring ai,  我也不是 chatgpt, 用的免费的 llama3, 很香
