### ISSUE TITLE
🧐[问题]配置流式输出问题

### ISSUE THREAD

**Issue by PeiJM** [ant-design/pro-chat#173]
### 🧐 问题描述
自己开的后台服务,自己组装 Reader 老是会报各种各样的错误,使用 详见 Github [ChatGPT-NextJs](https://github.com/ant-design/pro-chat/tree/main/demos/chatgpt-nextjs) 说的这个里边 demos/chatgpt-nextjs/src/app/api/openai/route.ts 的这个文件的代码 request: Request 参数不知道是什么 没有找到使用示例  .按照官网 使用三方 Reader 解析器解决方案 
const openai = new OpenAI({
  apiKey: "OpenAI-Key",
  baseurl:"" // 绝对路径跨域 相对路径url不符合规范
});
这个里边去使用 baseurl填写相对路径 报错url不规范,使用绝对路径 又报跨域 真的累了 搞了1天 求求给个明明白白的示例把

**Comment by PeiJM** [comment]
下面四张图片是对应图片配置和效果,效果都不对 帮忙看一下到底咋回事啊 谢谢@ONLY
![三方库配置效果](https://github.com/ant-design/pro-chat/assets/67719338/7a218bc4-9eb1-459b-b1ae-b51a74203144)
![使用三方库配置](https://github.com/ant-design/pro-chat/assets/67719338/b12b0fb5-8131-45ac-8253-eeb02a3e2eb8)
![正常配置](https://github.com/ant-design/pro-chat/assets/67719338/d24bc8d1-8ae6-444b-9ba3-abf54b40baba)
![正常配置后效果图](https://github.com/ant-design/pro-chat/assets/67719338/6d1a51cf-d996-4849-94eb-240d44dfd2b6)

**Comment by ONLY-yours** [comment]
@PeiJM 看起来你这个结构和这个 demo 里面的很类似

https://pro-chat.antdigital.dev/components/pro-chat#sse-%E6%95%B0%E6%8D%AE%E6%B5%81%E5%A4%84%E7%90%86

![image](https://github.com/ant-design/pro-chat/assets/52664827/55095e06-a00f-425e-94dc-594783c47678)

参造这里写一个 reader 去处理这个
