### ISSUE TITLE
🐛[BUG] 在next.js使用中发现的问题

### ISSUE THREAD

**Issue by PeiJM** [ant-design/pro-chat#177]
### 🧐 问题描述1

打包报错

###  报错信息

Generating static pages (0/5)  [=   ]Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Project\gsxm\next-chat\node_modules\shiki\dist\bundle-web.mjs not supported.
Instead change the require of D:\Project\gsxm\next-chat\node_modules\shiki\dist\bundle-web.mjs to a dynamic import() which is available in all CommonJS modules.

### 🧐 问题描述2

不知道是什么问题会报错

###  报错信息
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### 🧐 问题描述3

弃用警告

###  报错信息

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

### 版本信息

"@ant-design/pro-chat": "^1.13.1",
"antd": "^5.16.4",
"antd-style": "^3.6.2",
"next": "14.2.2",
"react": "^18",
"react-dom": "^18"

**Comment by AmAzing129** [comment]
https://github.com/ant-design/pro-chat/issues/266
