### ISSUE TITLE
👑 [需求] 流式支持，不是流式返回后收集所有响应再效果上实现打字

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-chat#182]
### 🥰 需求描述
看了现有的都是在接收完流式响应的内容后，前端伪装出的打字效果，或许是我的使用方式不对

想要的就是收到一个流式响应后实时的追加消息上去，或者提供更新消息的API

**Comment by ONLY-yours** [comment]
@beeant0512 直接返回一个 流式的 readable stream 就好了
