### ISSUE TITLE
🐛[BUG] html 会添加额外的textarea

### ISSUE THREAD

**Issue by LCJove** [ant-design/pro-chat#193]
### 🐛 bug 描述

在使用 proChat 之后，会在 html 的 body 中添加莫名的 textarea

### 📷 复现步骤

引入proChat即可
![image](https://github.com/ant-design/pro-chat/assets/31850902/d1a2f9be-367d-481f-a66d-754f005207b6)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.13.3]
- 浏览器环境 Chrome
- 开发环境 mac OS

**Comment by ONLY-yours** [comment]
排查后可忽略，这是antd 的 TextArea 添加了 AutoSize 后默认会加上的能力。
