### ISSUE TITLE
🧐[问题] 消息气泡中单词被分割开

### ISSUE THREAD

**Issue by umnooob** [ant-design/pro-chat#206]
### 🧐 问题描述

消息中的英文单词会被断开，如何保证单词在同一行不被断开呢

### 🚑 其他信息

<img width="288" alt="image" src="https://github.com/ant-design/pro-chat/assets/41941089/22689dcb-db4a-4ce1-99b7-71f92223aea0">

**Comment by ONLY-yours** [comment]
@umnooob 加一下 css 吧。默认是 wrap 的，你通过 ContentRender 给外面加一层 div ，然后给下面所有的 p 标签通过 css 关闭掉这个 wrap 的属性就好了

![image](https://github.com/ant-design/pro-chat/assets/52664827/d01b9e7d-d752-4326-88cc-c4ff7bedee9c)

**Comment by umnooob** [comment]
感谢！
