### ISSUE TITLE
🧐[问题] 是否支持 聊天框 的能力，发送消息后，机器人不主动回复，对面用户按需回复。

### ISSUE THREAD

**Issue by zhanyeye** [ant-design/pro-chat#210]
### 🧐 问题描述

想借助 ProChat 实现一个 聊天框的能力，发送消息后，不需要理解回复，应该如何实现呢，谢谢。

**Comment by ONLY-yours** [comment]
使用 InputAreaRender 重写发送框，参考 https://pro-chat.antdigital.dev/guide/multimodal 进行改造，然后不主动发送 request 的内容。

使用 ChatRef 的 pushChat 或者 setChats 受控往里面塞内容即可。例如：https://pro-chat.antdigital.dev/guide/servers-push
