### ISSUE TITLE
👑 [需求]增加onScroll的监听

### ISSUE THREAD

**Issue by songzhenjin** [ant-design/pro-chat#219]
### 🥰 需求描述
渲染上百条数据时存在卡顿。所以，用户期望可以滑动到顶部时，请求数据重新渲染，但现在ProChat没有透出监听滚动的事件方法

**Comment by hi-asan** [comment]
是的，我也需要，我尝试在 在 useEffect中执行
```json
 document.querySelector(".ant-pro-chat-chat-list-container").addEventListener("scroll",(e)=>console.log(e))
```
但始终不触发。setTimeout延后执行也无法触发，但是在浏览器控制台中执行。是能够触发的。 @songzhenjin 这个方案你试过吗？

这个方案行不通，只能等官方暴露出这个事件了。

**Comment by hi-asan** [comment]
如果我要插入历史消息呢？目前通过chats去设置，会导致重新渲染。有没有类似pushChat的行为，比如：unshiftChat @ONLY-yours
