### ISSUE TITLE
👑 [需求]暴露可操作区域的更多ref

### ISSUE THREAD

**Issue by songhanlin** [ant-design/pro-chat#226]
### 🥰 需求描述

需要编辑一大段文案, 然后进行某些操作, 插入一些文本到光标处, antd的input添加ref就可以实现, 但是会需要重写更多的能力, 包括重绘输入框的ui, 希望官方支持

**Comment by ONLY-yours** [comment]
详细阐述下？我没特别明白，是底部输入框区域的一些特定能力透出？现在是有 inputAreaProps 可以直接透传过去

**Comment by songhanlin** [comment]
例如我有一个快速插入功能, 可能会在输入框的一段文字中的光标处插入一段话, antd的input的ref可以实现这个功能, 但是我尝试在prochat的input中添加ref, 没有效果

**Comment by songhanlin** [comment]
例如, 推荐对话, "给[xx]生成小红书文案", 然后光标放在[]中, 外部有一个快捷插入, 然后把业务的内容插入到光标处

**Comment by songhanlin** [comment]
ref

> 例如我有一个快速插入功能, 可能会在输入框的一段文字中的光标处插入一段话, antd的input的ref可以实现这个功能, 但是我尝试在prochat的input中添加ref, 没有效果

拿不到ref, 是ref.current是null

**Comment by songhanlin** [comment]
我想修复这个问题, pr的message的前缀应该用什么 @ONLY-yours

**Comment by songhanlin** [comment]
![chrome-capture-2024-5-29](https://github.com/ant-design/pro-chat/assets/22296845/00da12ce-b37f-40ca-ab20-fc355119167c)
