### ISSUE TITLE
🐛[BUG] OverrideStyle 中的全局样式影响太大

### ISSUE THREAD

**Issue by gin-lsl** [ant-design/pro-chat#228]
### 🐛 bug 描述

https://github.com/ant-design/pro-chat/blob/9f2434da9a433e7f63f82eef8b4f29199f81056a/src/ProChat/container/OverrideStyle/global.ts#L22-L36

这里的全局样式影响太大了点。其他的暂时还没有发现，但是 `::selection` 带来的视觉影响稍微有点严重：

1. 我们有黑底白字的设计，这里选中状态文本颜色会变成黑色：
    ![image](https://github.com/ant-design/pro-chat/assets/18319675/de0278a8-95d1-4bff-9c9e-b284982f362a)

2. 我们有彩色字体的设计，这里选中状态文本直接看不到了：
    ![image](https://github.com/ant-design/pro-chat/assets/18319675/37f51375-db8f-4506-92d7-683c55499a26)

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LCJove** [comment]
@gin-lsl 曾老师来个pr吧哈哈

**Comment by gin-lsl** [comment]
> @gin-lsl 曾老师来个pr吧哈哈

嗯嗯，在看了，今天忙完了会有空🤠
