### ISSUE TITLE
🐛[BUG] 移动端下ProChat组件在PageContainer组件中对话遮挡

### ISSUE THREAD

**Issue by jiabochao** [ant-design/pro-chat#23]
### 🐛 bug 描述

移动端下ProChat组件在PageContainer组件中对话遮挡。

<img width="441" alt="image" src="https://github.com/ant-design/pro-chat/assets/16523012/fe90fae7-0d6c-4767-ba4f-d0e52b714306">

### 📷 复现步骤

将ProChat组件放在在PageContainer组件中，PageContainer默认有一个padding，但是ProChat container默认宽度100vw

### 🏞 期望结果

对话内容不遮挡。

想只去掉PageContainer body的padding是最好的，尝试了将PageContainer 的token：paddingInlinePageContainerContent设为0，但是会影响header和其他界面。不知道怎么弄了。

把ProChat container默认宽度设为100%，这种好像可以避免遮挡，但是还是有一个很大的padding。

### 💻 复现代码

```
<PageContainer
  header={{
    ghost: true,
    extra: [
    ],
  }}
>
  <ProChat
    style={{ height: 'calc(100vh - 160px)' }}
    showTitle
    userMeta={{
      avatar: '/user.svg',
      title: 'user',
    }}
    assistantMeta={{ avatar: '/openai.svg', title: 'ChatGPT' }}
    actions={{
      render: (defaultDoms) => {
        return [
          ...defaultDoms,
        ];
      },
      flexConfig: {
        gap: 24,
        direction: 'horizontal',
        justify: 'space-between',
      },
    }}
    request={''}
  />
</PageContainer>
```

### © 版本信息

- @ant-design/pro-chat 版本: 0.7.0
- 浏览器环境: Google Chrome 119.0.6045.123
- 开发环境: mac OS

**Comment by ONLY-yours** [comment]
好问题，感觉是应该改成 100% 会更好一些，不知道会不会带来什么问题。

**Comment by ONLY-yours** [comment]
已经修了

**Comment by jiabochao** [comment]
> 已经修了

确认已修复，感谢更新~
