### ISSUE TITLE
🐛[问题]  生成消息的时候发生窗口抖动

### ISSUE THREAD

**Issue by Rwentfose** [ant-design/pro-chat#245]
### 🐛 bug 描述

每次显示内容的时候当新的一行中的字体大小因为md格式的不同导致聊天窗口频繁抖动（滚动条）能不能在生成字体的时候固定行高，要不然消息在窗口上抖的

### 📷 复现步骤

[bug.MOV.zip](https://github.com/user-attachments/files/15739234/bug.MOV.zip)

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhangchenna** [comment]
插眼，同样的问题，出现滚动条，就会抖动
