### ISSUE TITLE
🧐[问题] 组件允许不渲染头像

### ISSUE THREAD

**Issue by Superskyyy** [ant-design/pro-chat#249]
### 🧐 问题描述

请问有没有办法在不渲染机器人头像的情况下直接输出文本呢，我们的使用场景有些不需要用户输入，直接让模型输出即可，也就不需要对话形态的头像了。

**Comment by Superskyyy** [comment]
![image](https://github.com/ant-design/pro-chat/assets/26076517/48c60283-e2a0-4792-bdd4-dfe3035627a1)
类似于这样但是顶格写

**Comment by ONLY-yours** [comment]
ChatItemConfig 里面的 AvatarRender 就可以了，渲染为空就好
