### ISSUE TITLE
🐛[BUG] 调整页面比例后聊天框一直逐渐变小

### ISSUE THREAD

**Issue by sinianluoye** [ant-design/pro-chat#251]
### 🐛 bug 描述

调整页面比例后聊天框会逐渐变小，官网组件页即可复现

### 📷 复现步骤

调整页面比例后聊天框会逐渐变小，官网组件页即可复现

[vedio](https://github.com/ant-design/pro-chat/assets/19305777/57650263-7557-4f46-9bb5-ef2be3939410)

### 🏞 期望结果

不触发此类效果

### 💻 复现代码

官网组件页即可复现

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- edge 

### 🚑 其他信息

已经在个人fork的仓库中进行修复 https://github.com/sinianluoye/pro-chat/pull/2/files

bug触发的原因是src/ProChat/container/App.tsx下 RcResizeObserver组件的onResize函数调用setHeight后height和e.height始终存在一个很小的差值，导致一直触发onResize事件
```tsx
onResize={(e) => {
          if (e.height !== height) {
            setHeight(e.height);
          }
}
```
修改后的代码为

```tsx
onResize={(e) => {
          if ((typeof height !== typeof e.height) ||
              (typeof height === 'string' && typeof e.height === 'string' && e.height !== height) || 
              (typeof height === 'number' && Math.abs(e.height - height) > 1)) { 
              // 加一个 Math.abs(e.height - height) > 1 的判断以避免height和e.height相差过小导致的页面一直缩小
              setHeight(e.height);
          }
        }}
```

**Comment by ONLY-yours** [comment]
神奇的 bug 哈哈哈

**Comment by ONLY-yours** [comment]
@sinianluoye 直接给我们提一个 pr 合并进来呢 哈哈哈
