### ISSUE TITLE
🐛[BUG] 使用 StreamingTextResponse ts 报语法错误

### ISSUE THREAD

**Issue by yuruotong1** [ant-design/pro-chat#254]
### 🐛 bug 描述

我的代码为：
![image](https://github.com/ant-design/pro-chat/assets/31992251/e2d7932c-e2a8-4d37-840e-c8eeeac0cc82)

![image](https://github.com/ant-design/pro-chat/assets/31992251/c7b0afec-a361-4442-9dd2-aca55335c6b7)

详细错误信息如下：

```
Type '(messages: Record<string, any> & ModelConfig) => Promise<StreamingTextResponse>' is not assignable to type 'ChatListRequest<Record<string, any>>'.
  Type 'Promise<StreamingTextResponse>' is not assignable to type 'Promise<ChatMessage<Record<string, any>>[]>'.
    Type 'StreamingTextResponse' is missing the following properties from type 'ChatMessage<Record<string, any>>[]': length, pop, push, concat, and 35 more.ts(2322)
```

**Comment by ONLY-yours** [comment]
应该是这个 ai 包升级导致了用法发生了变化，文档需要更新下了

**Comment by yuruotong1** [comment]
> 应该是这个 ai 包升级导致了用法发生了变化，文档需要更新下了

请问大佬能不能发一下最新的用法，新版本的ai已经废弃掉了文档的用法！

**Comment by ONLY-yours** [comment]
稍后我看看把文档更新一版本，还没来得及看新的用法

**Comment by yuruotong1** [comment]
> 稍后我看看把文档更新一版本，还没来得及看新的用法

感谢您的回复，期待文档更新！

**Comment by ONLY-yours** [comment]
```ts
import { createOpenAI } from '@ai-sdk/openai';
import { StreamingTextResponse, streamText } from 'ai';

export async function POST(request: Request) {
  const { messages = [] }: Partial<{ messages: Array<any> }> = await request.json();

  const PickMessages = messages.map((message) => {
    return {
      role: message.role,
      content: message.content,
    };
  });

  const openai = createOpenAI({
    // custom settings, e.g.
    apiKey: 'OpenAI Key', // your openai key
    baseURL: 'base url', // if u dont need change baseUrl，you can delete this line
    compatibility: 'compatible',
  });
  const stream = await streamText({
    model: openai('gpt-3.5-turbo'),
    messages: [...PickMessages],
  });
  return new StreamingTextResponse(stream.textStream);
}
```

文档在更新中，可以参考这个例子。

**Comment by yuruotong1** [comment]
> ```ts
> import { createOpenAI } from '@ai-sdk/openai';
> import { StreamingTextResponse, streamText } from 'ai';
> 
> export async function POST(request: Request) {
>   const { messages = [] }: Partial<{ messages: Array<any> }> = await request.json();
> 
>   const PickMessages = messages.map((message) => {
>     return {
>       role: message.role,
>       content: message.content,
>     };
>   });
> 
>   const openai = createOpenAI({
>     // custom settings, e.g.
>     apiKey: 'OpenAI Key', // your openai key
>     baseURL: 'base url', // if u dont need change baseUrl，you can delete this line
>     compatibility: 'compatible',
>   });
>   const stream = await streamText({
>     model: openai('gpt-3.5-turbo'),
>     messages: [...PickMessages],
>   });
>   return new StreamingTextResponse(stream.textStream);
> }
> ```
> 
> 文档在更新中，可以参考这个例子。

@ONLY-yours 

我试了一下 pro-chat 组件还是报错，报错信息：

![image](https://github.com/ant-design/pro-chat/assets/31992251/b3bf24b0-c472-44d9-b5bf-c27c6e0ab365)


我的代码是这么写的：

```js
 <div style={{ background: theme.colorBgLayout }}>
    <ProChat
        helloMessage={
            '你好，我叫智子，你的智能Agent助手！有什么要求可以随时吩咐！'
        }
        request={async (messages) => {
            console.log('messages', JSON.stringify(messages))
            const response = await useChat(JSON.stringify(messages))
            // 使用 Message 作为参数发送请求
            return response// 支持流式和非流式
    }}
  />
  </div>
```
import { StreamingTextResponse, streamText } from "ai";
import { createOpenAI } from '@ai-sdk/openai';

export async function useChat(messages: any){
  const configType =  await window.api.getConfig()
  const llm = JSON.parse(JSON.parse(configType.content).llm)

  const openai = createOpenAI({
    // custom settings, e.g.
    apiKey: llm.apiKey, // your openai key
    baseURL: llm.baseURL, // if u dont need change baseUrl，you can delete this line
    compatibility: 'compatible',
  });
  const stream = await streamText({
    model: openai(llm.model),
    messages: messages,
  });
  console.log('stream', stream)
  return new StreamingTextResponse(stream.textStream);
}


```js

```

**Comment by ONLY-yours** [comment]
@yuruotong1 我试了下，应该是没问题的，确定下版本：

```json
    "ai": "^3.2.0",
    "openai": "^4.24.7",
    "@ai-sdk/openai": "^0.0.33",

```

**Comment by yuruotong1** [comment]
> @yuruotong1 我试了下，应该是没问题的，确定下版本：
> 
> ```json
>     "ai": "^3.2.0",
>     "openai": "^4.24.7",
>     "@ai-sdk/openai": "^0.0.33",
> ```

我看了你的 demo 代码，你用的 pro-chat 好像不是最新版本？

我用的版本是：
```js
"@ant-design/pro-chat": "^2.1.14",
```
