### ISSUE TITLE
🧐[问题]server Error / TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by fxz19901123** [ant-design/pro-chat#259]
### 🧐 问题描述

 "next": "14.2.4", pagesRouter ,按照要求添加了transpilePackages配置。启动项目后，报错。

Call Stack
map
node_modules/@ant-design/pro-editor/es/Markdown/wrapper.js (11:35)
Next.js
eval
/node_modules/@ant-design/pro-editor/es/Markdown/wrapper.js
./node_modules/@ant-design/pro-editor/es/Markdown/wrapper.js
file:///Users/Annce/Desktop/tools/timeline-frontend/.next/server/vendor-chunks/@ant-design.js (19140:1)
Next.js
eval
/node_modules/@ant-design/pro-editor/es/Markdown/CodeBlock.js
Next.js
eval
/node_modules/@ant-design/pro-editor/es/Markdown/CodeBlock.js
./node_modules/@ant-design/pro-editor/es/Markdown/CodeBlock.js
file:///Users/Annce/Desktop/tools/timeline-frontend/.next/server/vendor-chunks/@ant-design.js (19110:1)
Next.js
eval
/node_modules/@ant-design/pro-editor/es/Markdown/index.js
Next.js
eval
/node_modules/@ant-design/pro-editor/es/Markdown/index.js
./node_modules/@ant-design/pro-editor/es/Markdown/index.js
file:///Users/Annce/Desktop/tools/timeline-frontend/.next/server/vendor-chunks/@ant-design.js (19120:1)
Next.js

**Comment by AmAzing129** [comment]
目测 @ant-design/pro-editor transpile 未生效，最新版本的 nextjs 正确配置不会存在问题，请提供具体代码复现，先关闭了
