### ISSUE TITLE
🧐[问题]项目执行npm run build 报错 

### ISSUE THREAD

**Issue by XPStone** [ant-design/pro-chat#266]
### 🧐 问题描述
执行npm run build 报错，求助

![image](https://github.com/ant-design/pro-chat/assets/64072854/a05a3739-3a44-40fb-b352-e6db19c8ec83)，
执行npm install shiki@latest后再build，虽然显示build的成功，但proChat的版本改为^2.15.1，项目会爆红，改回^1.14.2后重新build会一样报错。

**Comment by ONLY-yours** [comment]
嗯，2.x 版本还不能用的，所以只能用 1.x

**Comment by ONLY-yours** [comment]
新的 nextjs 确实有这个问题，我来解下

**Comment by ONLY-yours** [comment]
@XPStone 暂时不影响使用，记得标注为 'use client'，我得看看 shiki 怎么做兼容 SSR

**Comment by XPStone** [comment]
> @XPStone 暂时不影响使用，记得标注为 'use client'，我得看看 shiki 怎么做兼容 SSR
嗯，不影响开发，但暂时是没有办法部署

**Comment by XPStone** [comment]
> @XPStone 暂时不影响使用，记得标注为 'use client'，我得看看 shiki 怎么做兼容 SSR

你好，如果我现在想build这个项目的话，您有什么方案吗？

**Comment by AmAzing129** [comment]
> > @XPStone 暂时不影响使用，记得标注为 'use client'，我得看看 shiki 怎么做兼容 SSR
> 
> 你好，如果我现在想build这个项目的话，您有什么方案吗？

next.js 增加配置：
```
const nextConfig = {
  transpilePackages: ['shiki'],
};
```
