### ISSUE TITLE
👑 [需求] 需要一个 ChatGPT 的 demo 

### ISSUE THREAD

**Issue by ONLY-yours** [ant-design/pro-chat#30]
### 🥰 需求描述

需要产出一个 ChatGPT 的 demo
最好还需要一篇文档《使用 ProChat 接入 ChatGPT》类似的文档，让大家可以参照用起来

**Comment by ONLY-yours** [comment]
@jiabochao 哥们，感兴趣能给我们提一个 pr 共建下嘛

**Comment by jiabochao** [comment]
> @jiabochao 哥们，感兴趣能给我们提一个 pr 共建下嘛

可以的呀，正好我也在搞这个，其实已经有一些demo了，可以根据我们的具体需求改改。

**Comment by k7cd** [comment]
请问后端接口怎么在demo中启起来?

**Comment by ONLY-yours** [comment]
> 请问后端接口怎么在demo中启起来?

看你前端用的什么框架 我们官网有提供 NextJs 下的 qwen 和 chatgpt 的案例：

https://pro-chat.antdigital.dev/guide/qwen

基本上浏览器 fetch 或者 axios 请求到网络就可以，没有特殊要求

**Comment by Tss-16** [comment]
ProChat组件怎么更改聊天框样式啊？

**Comment by ONLY-yours** [comment]
GPT demo 补齐了，这个贴先关闭了
