### ISSUE TITLE
👑 [需求] helloMessage 能在用户发送一条消息之后, 还保留吗?

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/pro-chat#306]
### 🥰 需求描述

 helloMessage 能在用户发送一条消息之后, 还保留吗?
现在的场景, 就是发送 一条信息之后 helloMessage就没有了, 我们可以让 helloMessage 保留吗? 即使发送了一条 问题之后

### 🧐 解决方案

即使发送了一条 问题之后 任然 保留helloMessage;

**Comment by ONLY-yours** [comment]
不行，HelloMessage 目的就是为了让用户初始化没有对话时候展示的，如果保留的话，直接使用受控的方式 或者 initValue 给进去就好了
