### ISSUE TITLE
👑 [需求]国际化

### ISSUE THREAD

**Issue by scarqin** [ant-design/pro-chat#56]
### 🥰 需求描述

希望有国际化方案，默认英文

### 🧐 解决方案

i18next

### 🚑 其他信息

需要的话我可以做

**Comment by ONLY-yours** [comment]
欢迎给我们来个 pr 🥰

**Comment by LCJove** [comment]
> 欢迎给我们来个 pr 🥰

你有什么建议吗，打算搞一个locale的package专门搞国际化

**Comment by ONLY-yours** [comment]
> > 欢迎给我们来个 pr 🥰
> 
> 你有什么建议吗，打算搞一个locale的package专门搞国际化

其实该组件不需要什么复杂的改造，placerholder 修改输入框的提示 + sendButtonText 修改下发送按钮的提示，其实就足够了。

**Comment by ONLY-yours** [comment]
更需要的可能是文档的国际化，现在文档全是中文的

**Comment by AIAnytime** [comment]
> > What is more needed may be the internationalization of documents. Now the documents are all in Chinese.
> 
> Then let’s do it in a lightweight way

How can we do this for English? Where to make changes? which file?
