### ISSUE TITLE
🐛[BUG] 单独使用  <ChatItem> message属性接收ReactNode 显示 [object Object]

### ISSUE THREAD

**Issue by lhtfuture** [ant-design/pro-chat#60]
### 🐛 bug 描述
单独使用  <ChatItem> message属性接收ReactNode 显示 [object Object]

### 🏞 期望结果
message应该显示接收的 ReactNode ，这个问题在 messageExtra不存在

### 💻 复现代码
https://pro-chat.antdigital.dev/components/chat-item，可参考官方文档

### © 版本信息

- @ant-design/pro-chat 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/pro-chat/assets/131160101/f462e6d9-f36f-40bc-9d08-ae28963cdecb)
![image](https://github.com/ant-design/pro-chat/assets/131160101/2b539fd0-1edb-48a3-811f-2f14c18fccff)

**Comment by arvinxx** [comment]
目前 message 只支持 string。 原因是默认的 message 是支持编辑的，考虑下编辑场景的 ReactNode 该怎么展现？

**Comment by lhtfuture** [comment]
@arvinxx 感谢解惑，由于对应的type.d.ts里面message的类型是ReactNode，因此以为可以传 ReactNode。
![image](https://github.com/ant-design/pro-chat/assets/131160101/dbb1068c-be8a-4e71-a623-6233b39c278a)

**Comment by lhtfuture** [comment]
@arvinxx 感谢解惑，由于对应的type.d.ts里面message的类型是ReactNode，因此以为可以传 ReactNode。
