### ISSUE TITLE
👑 [需求]    需要支持html 的文档的渲染

### ISSUE THREAD

**Issue by ximao480** [ant-design/pro-chat#61]

**Comment by ONLY-yours** [comment]
底层组建 ProEditor 我们有留口子，我开一个 api 支持配置透传好了

**Comment by maxoo1001** [comment]
那echarts之类的 这些也可以用这个api配置透传嘛?  这个api是否支持好了? @ONLY-yours

**Comment by ONLY-yours** [comment]
> 那echarts之类的 这些也可以用这个api配置透传嘛? 这个api是否支持好了? @ONLY-yours

现在可以先用 messageItemExtraRender 这个 api 进行渲染，echarts 在走 markdown 渲染总觉得不是好想法
