### ISSUE TITLE
「RFC」ProChat Request 结构设计

### ISSUE THREAD

**Issue by ONLY-yours** [ant-design/pro-chat#7]
需要一个通用的 Request 的结构设计，可以让大模型的接口通用的使用。
### 语言模型接口分析
这里参考了一些模型、平台、框架、服务商（GLM、GPT、OpenAI、Azure、LangChain等）
整体来说，不同模型都是 follow ChatGPT 的设计思路，可以看到除了框架层，模型层的入参和回参都是类似的。
#### 请求参数解析
```bash
curl https://api.openai.com/v1/chat/completions   
-H "Content-Type: application/json"   
-H "Authorization: Bearer $OPENAI_API_KEY"   
-d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."
      },
      {
        "role": "user",
        "content": "Compose a poem that explains the concept of recursion in programming."
      }
    ]
  }'
```
整体来说请求参数分为以下几个部分：

- messages（prompt）：包含上下文的对话记录
- apiKey：用于请求网络数据的 api key。（这个参数一般放在 env 中，在请求头中带入，因此设计可以略过该参数）
- model：模型的参数，例如当前使用的是什么模型。
- params（config、settings）：MaxToken、Top_P 这一类和请求有关的参数设置
- steam：是否是流式输出
- plugin（function_call）：如果有插件体系，会带上这个（function_call也被认为是一个特殊的 plugin）
> 这里不讨论：t2image、t2voice、embedding、Speech2text 这些特殊情况，
> 一来是这些并不是所有对话模型支持的，我们需要设计的是一个通用接口
> 二来是就算接口支持，这些对于不同的模型接口也会有不同的设计，很难统一
> 这些额外的内容，我们提供一个类似 ProComponets 中的 Pramas ，用额外参数的形式让用户自己塞进来。

#### 回参分析
```json
{
    "status_code": 200,
    "request_id": "05dc83af-7185-9e14-9b0b-4466de159d6a",
    "code": "",
    "message": "",
    "output": {
        "text": null,
        "finish_reason": null,
        "choices": [
            {
                "finish_reason": "stop",
                "message": {
                    "role": "assistant",
                    "content": "首先，准备两个鸡蛋，一个西红柿，适量的盐、糖、料酒和生抽。将鸡蛋打入碗中，搅拌均匀，西红柿切块。锅中加油，油热后加入鸡蛋液，炒至金黄色，盛出备用。锅中加油，油热后加入西红柿块，翻炒均匀，加入适量的盐、糖、料酒和生抽，炒至西红柿软烂，加入炒好的鸡蛋，翻炒均匀即可。"
                }
            }
        ]
    },
    "usage": {
        "input_tokens": 12,
        "output_tokens": 98,
        "total_tokens": 110
    }
}
```
对于是否流式输出，可以分为两种 流式（[Server-sent_events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)） 和 非流式：
从 ProChat 最关键的能力来说，有几个东西是必须的：

- message（choices）：当前返回的对话内容（可能是一个结构，{ role, content } ）
- usage：本次内容的一些 token 信息（用多少 token、还剩下多少）
- request_id：用于标识当前对话的唯一 id，可有也可以没有，甚至可以前端生成
- status_code：状态码，主要为了错误返回时候的设计
- finished（finish_reason、finish_flag）：返回的终止符号（只有流式情况需要返回）
> 不对流式和非流式做特殊处理，如果是流式，内容组装也放在 request 里面做，返回结构依然按照这四个进行组合，对于非流式来说，request 只会触发一次，流式则会在结束前，不停的触发 request ，用 finished 这种标志内容来进行结束的判定。

#### ErrorCode 设计
主要参考 OpenAI

| ** CODE** | ** OVERVIEW** |
| --- | --- |
| 401 - 无效的身份验证 | 原因：身份验证无效
解决方案：确保使用正确的 API 密钥和请求组织。 |
| 401 - 提供的 API 密钥不正确 | 原因：请求的 API 密钥不正确。
解决方案：确保使用的 API 密钥正确无误，清除浏览器缓存，或生成新的密钥。 |
| 401 - 您必须是组织的成员才能使用 API | 原因：您的帐户不是组织的一部分。
解决方案：联系我们以添加到新组织，或让您的组织经理邀请您加入组织。 |
| 429 - 已达到请求的速率限制 | 原因：您发送请求的速度太快。
解决方案：调整请求的节奏。阅读速率限制指南。 |
| 429 - 您超出了当前的配额，请检查您的计划和账单明细 | 原因：您已达到每月最高支出，您可以在限制页面上查看该支出。
解决方案：申请增加配额。 |
| 500 - 服务器在处理您的请求时出错 | 原因：我们的服务器存在问题。
解决方案：稍等片刻后重试您的请求，如果问题仍然存在，请与我们联系。检查状态页面。 |
| 503 - 引擎当前过载，请稍后再试 | 原因：我们的服务器流量很大。
解决方案：请在短暂等待后重试您的请求。 |

不同的 errorCode 对应不同的错误提示，我们默认内置这些状态反馈，后续可以通过类似 ErrorCodeEnum 进行自定义配置，当然这次不是讨论该内容。

### Request 入参设计
```tsx
type Message = {
  role: string,
  content: string,
}

type Params = {
  maxTokens?: number,
  topP?: number,
  // 可根据需要添加更多参数
}

type FunctionCall = {
  function: string,
  from: string,
  message: string,
  to: string,
}

type Model = {
	name: string,
	modelhash: string,
}

interface RequestProps {
  messages: Message[],
  model: Model,
  params: Params,
  stream: boolean,
  functionCall?: FunctionCall,
  extraParams?: any,
}


```
### Response 返回设计
```tsx
interface Usage {
  totalTokens: number;
  inputTokens: number;
  outputTokens: number;
}

interface Message {
  role: string;
  content: string;
}

interface ResponseProps {
  message: Message
  usage: Usage;
  requestId?: string;  // 根据需求，这个字段是可选的
  statusCode: number;
  finished?: boolean;  // 当API返回是流式输出时，结束时候返回true；
}
```

### 使用示例
```bash
<ProChat
	request={(data: RequestProps)=>{
      const {
        messages = [],
        model = { name:'gpt3.5-turbo', modelhash:"#3xasdw613md" },
        params,
        stream,
        functionCall,
        extraParams,
      } = data || {}
      
      // TODO
      const Response = await request(xxxx,{
        // TODO 网络请求
      })

    	return {
        	message: {
              "role": "assistant",
              "content": "你好 我是你的私人"    
          },
          finished: false,
          requestId: 'request-id-312dsaniuhawemda'
          usage:{
          		totalTokens: 5000
              inputTokens: 20
              outputTokens: 30
          }
          statusCode: 200
      }
  }}
/>
```

**Comment by rdmclin2** [comment]
functionCall 暂时没有必要
