### ISSUE TITLE
🧐[问题] 官网给出来的案例是否是老版本的?还是什么其他原因?

### ISSUE THREAD

**Issue by maxoo1001** [ant-design/pro-chat#72]
### 🧐 问题描述
我在尝试使用这个组件的时候,使用了官网给出来的示例,然后一直报错,是否有问题?  版本都是按照要求来的
https://pro-chat.antdigital.dev/guide/nextjs
'use client';
import { useState, useEffect } from 'react';
import { ProChat } from '@ant-design/pro-chat';
export default () => (
  <ProChat
    style={{
      height: '100vh',
      width: '100vw',
    }}
    **request={async (messages) => {**
       helloMessage={
          '欢迎使用 ProChat ，我是你的专属机器人，这是我们的 Github：[ProChat](https://github.com/ant-design/pro-chat)'
        }
        **request={async (messages) => {**
          const mockedData: string = `这是一段模拟的对话数据。本次会话传入了${messages.length}条消息`;
          return new Response(mockedData);
        }}
    }}
  />
);

### 🚑 其他信息

这边给出来的示例代码是否是错的?我去掉了第一**个request={async (messages) =>** 以后,   代码能正常运转了?

**Comment by ONLY-yours** [comment]
能贴一下报错的信息么？

**Comment by maxoo1001** [comment]
![图片](https://github.com/ant-design/pro-chat/assets/44355914/352938cc-aaf0-4202-811a-fbbb24bd14bc)
报错如下,麻烦能否帮忙看看

**Comment by ONLY-yours** [comment]
> ![图片](https://private-user-images.githubusercontent.com/44355914/300755102-352938cc-aaf0-4202-811a-fbbb24bd14bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDgzMzYsIm5iZiI6MTcwNjYwODAzNiwicGF0aCI6Ii80NDM1NTkxNC8zMDA3NTUxMDItMzUyOTM4Y2MtYWFmMC00MjAyLTgxMWEtZmJiYjI0YmQxNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZTdkNTBlY2UwNzUxM2IxMjZlNjg2MDczZjI3ZDQ4MzI4NDJmOTZkMTYxZTYzZWI3OGQ0YTg5MzI5ZDcwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UqZ-pFzVJlZ4y7g6w2YFMfPr2efrcL86DYux3usgyns) 报错如下,麻烦能否帮忙看看

你好像写错了，48行的 helloMessage 和 47 行 的 request 方法是同层级的呢，你把 47行和 55 行一起删掉应该就好了

**Comment by ONLY-yours** [comment]
@maxoo1001 对不起，好像是我们在格式化的时候有点问题，你先手动删一下，我在文档上去掉这个
