### ISSUE TITLE
👑 [proChat是否能支持移动端？]

### ISSUE THREAD

**Issue by CaixyPromise** [ant-design/pro-chat#76]
### 🥰 需求描述

proChat做的非常好，美观大方。但是否有移动端的解决方案，想沿用支持，例如ReactNative，是否支持呢？谢谢

**Comment by ONLY-yours** [comment]
默认 H5 效果挺好的

![image](https://github.com/ant-design/pro-chat/assets/52664827/cc5cf5f7-119e-45ff-8184-3537f6d19935)

**Comment by ONLY-yours** [comment]
ReactNative 似乎不是很行？普通的 React 组件库应该没办法直接在 ReactNative 中使用。

**Comment by Bollie15** [comment]
> 默认 H5 效果挺好的
> 
> ![image](https://private-user-images.githubusercontent.com/52664827/301376574-cc5cf5f7-119e-45ff-8184-3537f6d19935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA1MTYsIm5iZiI6MTcwNzA0MDIxNiwicGF0aCI6Ii81MjY2NDgyNy8zMDEzNzY1NzQtY2M1Y2Y1ZjctMTE5ZS00NWZmLTgxODQtMzUzN2Y2ZDE5OTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA5NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhM2M0MjQyNzZjNTVkODBjNzM3MzAxZDAwY2Y4OTM2ZGQ3MGMyOGY3M2Y0NDM3NjVkMzc3MGRiNzQ5MzI2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSN4eiuAH47_MTon3cgWSfwkgRu52_bGhDtUmasin2E)

h5页面的布局有问题，你看下发送框里面的发送图标位置偏了。
另外屏幕较小时，能不能把头像显示当做可选，或者将头像放在气泡的上方（当前默认并排时，内容如果太多会导致气泡有个下拉条）

**Comment by ONLY-yours** [comment]
> > 默认 H5 效果挺好的
> > ![image](https://private-user-images.githubusercontent.com/52664827/301376574-cc5cf5f7-119e-45ff-8184-3537f6d19935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA1MTYsIm5iZiI6MTcwNzA0MDIxNiwicGF0aCI6Ii81MjY2NDgyNy8zMDEzNzY1NzQtY2M1Y2Y1ZjctMTE5ZS00NWZmLTgxODQtMzUzN2Y2ZDE5OTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA5NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhM2M0MjQyNzZjNTVkODBjNzM3MzAxZDAwY2Y4OTM2ZGQ3MGMyOGY3M2Y0NDM3NjVkMzc3MGRiNzQ5MzI2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSN4eiuAH47_MTon3cgWSfwkgRu52_bGhDtUmasin2E)
> 
> h5页面的布局有问题，你看下发送框里面的发送图标位置偏了。 另外屏幕较小时，能不能把头像显示当做可选，或者将头像放在气泡的上方（当前默认并排时，内容如果太多会导致气泡有个下拉条）

现在头像可以通过 chatItemRenderConfig 来进行很自定义，下面就可以帮你隐藏掉

```
chatItemRenderConfig={{
          avatarRender: ()=>{
            return <></>
          }
        }}
```

至于发送图标，不是偏了，而是直接被隐藏了，小屏幕的时候发送框的按钮就不展示了呢，设计使然

发送部分如果觉得布局不好可以使用 render 来自定义，我们补充了一个纯自定义的 demo

**Comment by Tss-16** [comment]
> > > 默认 H5 效果挺好的
> > > ![image](https://private-user-images.githubusercontent.com/52664827/301376574-cc5cf5f7-119e-45ff-8184-3537f6d19935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA1MTYsIm5iZiI6MTcwNzA0MDIxNiwicGF0aCI6Ii81MjY2NDgyNy8zMDEzNzY1NzQtY2M1Y2Y1ZjctMTE5ZS00NWZmLTgxODQtMzUzN2Y2ZDE5OTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA5NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhM2M0MjQyNzZjNTVkODBjNzM3MzAxZDAwY2Y4OTM2ZGQ3MGMyOGY3M2Y0NDM3NjVkMzc3MGRiNzQ5MzI2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSN4eiuAH47_MTon3cgWSfwkgRu52_bGhDtUmasin2E)
> > 
> > 
> > h5页面的布局有问题，你看下发送框里面的发送图标位置偏了。 另外屏幕较小时，能不能把头像显示当做可选，或者将头像放在气泡的上方（当前默认并排时，内容如果太多会导致气泡有个下拉条）
> 
> 现在头像可以通过 chatItemRenderConfig 来进行很自定义，下面就可以帮你隐藏掉
> 
> ```
> chatItemRenderConfig={{
>           avatarRender: ()=>{
>             return <></>
>           }
>         }}
> ```
> 
> 至于发送图标，不是偏了，而是直接被隐藏了，小屏幕的时候发送框的按钮就不展示了呢，设计使然
> 
> 发送部分如果觉得布局不好可以使用 render 来自定义，我们补充了一个纯自定义的 demo
发送部分如果想要在H5页面也显示发送按钮的话是在inputAreaProps里面操作吗？还是有其他的方法render啊？

**Comment by ONLY-yours** [comment]
> 发送部分如果想要在H5页面也显示发送按钮的话是在inputAreaProps里面操作吗？还是有其他的方法render啊？

@Tss-16 也可以参考文档里面的 自定义 render 来做，至于 inputAreaProps 则是只负责输入框的，目前还没设计 Button 部分的 api，感觉会需要一个 api 来自定义

```ts
inputAreaProps:{
  sendButtonProps:{
      icon: ReactNode;
      render: (props)=> ReactNode;
      onClick:()=>{}
      // others api 
  }
}

```

**Comment by Tss-16** [comment]
#

> > 发送部分如果想要在H5页面也显示发送按钮的话是在inputAreaProps里面操作吗？还是有其他的方法render啊？
> 
> @Tss-16 也可以参考文档里面的 自定义 render 来做: [Demo link](https://pro-chat.antdigital.dev/guide/multimodal#%E4%B8%80%E4%B8%AA%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%BC%94%E7%A4%BA%E6%A1%88%E4%BE%8B) 至于 inputAreaProps 则是只负责输入框的，目前还没设计 Button 部分的 api，感觉会需要一个 api 来自定义

inputAreaProps里的disabled属性不支持useState的变量更新吗？我用setIsDisabled变量来更新disabled的值 input组件可以实现禁用与否的更新 但是inputAreaProps里的disabled只能显示为第一次进页面的disabled的值

**Comment by ONLY-yours** [comment]
> > > 发送部分如果想要在H5页面也显示发送按钮的话是在inputAreaProps里面操作吗？还是有其他的方法render啊？
> > 
> > 
> > @Tss-16 也可以参考文档里面的 自定义 render 来做: [Demo link](https://pro-chat.antdigital.dev/guide/multimodal#%E4%B8%80%E4%B8%AA%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%BC%94%E7%A4%BA%E6%A1%88%E4%BE%8B) 至于 inputAreaProps 则是只负责输入框的，目前还没设计 Button 部分的 api，感觉会需要一个 api 来自定义
> 
> inputAreaProps里的disabled属性不支持useState的变量更新吗？我用setIsDisabled变量来更新disabled的值 input组件可以实现禁用与否的更新 但是inputAreaProps里的disabled只能显示为第一次进页面的disabled的值

新开一个 Issue 跟进下 @Tss-16 这个我先关闭了
