### ISSUE TITLE
🧐[问题]网站和github上面给的next.js Chatgpt的DEMO例子跑不通。。

### ISSUE THREAD

**Issue by maxoo1001** [ant-design/pro-chat#81]
### 🧐 问题描述
环境装的就是next.js +antd +ts  想整体按demo跑一遍
https://pro-chat.antdigital.dev/guide/chatgpt
https://github.com/ant-design/pro-chat/blob/main/demos/chatgpt-nextjs/src/app/chatgpt/index.tsx
这个上面显示的都是在掉千问的接口
![image](https://github.com/ant-design/pro-chat/assets/44355914/84f19283-0532-4c43-82db-933509cb5897)

但是根据openai/route.ts当作后端的api去跑又报了个错。能帮忙看看那个demo的问题吗？
![image](https://github.com/ant-design/pro-chat/assets/44355914/d836a5d5-7c57-4951-9dcf-113229ad48be)
@ONLY-yours

**Comment by ONLY-yours** [comment]
这里fetch 的 链接写的不对，我们有点失误，已经更新了。 /api/openai

其次就是 apiKey 和 BaseUrl 需要你写一下的，没有 token 例子也不会通

**Comment by ONLY-yours** [comment]
@maxoo1001 或者你直接拉我们具体 demo 到本地，然后 pnpm install 就可以了

**Comment by maxoo1001** [comment]
key这些我肯定都换过了，用的环境变量写的
api那个我手工修复过了应该也没问题
但是route.ts里面  就是api对应的后端代码。跑起来就会报  await request.json()说类型不匹配。这块不知道怎么解决。。

**Comment by ONLY-yours** [comment]
> key这些我肯定都换过了，用的环境变量写的 api那个我手工修复过了应该也没问题 但是route.ts里面 就是api对应的后端代码。跑起来就会报 await request.json()说类型不匹配。这块不知道怎么解决。。

对不起，看起来是我们的 bug  这个案例里面并不需要             const data = await response.json();
直接拿到后返回即可，稍后我会更新下 demo

```ts
 request={async (messages: Array<any>) => {
          const response = await fetch('/api/gpt', {
            method: 'POST',
            body: JSON.stringify({ messages: messages }),
          });
          return response
}

```

**Comment by ONLY-yours** [comment]
@maxoo1001 再试试，文档和 demo 我都更新上去了，之前的结构也有点奇怪，现在都调整了

**Comment by maxoo1001** [comment]
![image](https://github.com/ant-design/pro-chat/assets/44355914/e543e5c9-7309-44f6-b667-5ec80c0a759a)
我把项目demo完整down下来又跑了一次。还是报错  不过现在报错内容不一样了
BadRequestError: 400 Additional properties are not allowed ('createAt', 'id', 'meta', 'updateAt' were unexpected) - 'messages.0'
@ONLY-yours

**Comment by maxoo1001** [comment]
我好像知道是什么问题了。需要自己重新过滤一次对话内容。。实际的这个消息并不能实际像demo展示的这样直接使用。。

**Comment by ONLY-yours** [comment]
> 我好像知道是什么问题了。需要自己重新过滤一次对话内容。。实际的这个消息并不能实际像demo展示的这样直接使用。。

并不用自己过滤啊，你如果是官方的话，baseURL 都可以删掉

![image](https://github.com/ant-design/pro-chat/assets/52664827/9202ed38-3de6-44f3-97b5-4670f7fde7df)

**Comment by maxoo1001** [comment]
const correctedMessages = messages.map((message) => ({
    role: message.role,
    content: message.content,
  }));
我用这个把message里面过滤掉了'createAt', 'id', 'meta', 'updateAt'  以后能跑起来了。。。

**Comment by maxoo1001** [comment]
还是非常感谢你的帮助的，
我本身对编程和next.js都不是很懂。。基本每步都是按Demo和跟着GPT指示在学怎么做的。。github提这个issue也是才学会的。。pr不太会。。

**Comment by ONLY-yours** [comment]
> 还是非常感谢你的帮助的， 我本身对编程和next.js都不是很懂。。基本每步都是按Demo和跟着GPT指示在学怎么做的。。github提这个issue也是才学会的。。pr不太会。。

没问题，那我补充下我的 demo，确实是我们失误了给你造成了困扰 ：） 

后面欢迎来给我们提需求和 pr 哈哈哈

**Comment by ONLY-yours** [comment]
已经更新上去了，thank u again
