### ISSUE TITLE
👑 [需求]移动端头像和气泡显示

### ISSUE THREAD

**Issue by Bollie15** [ant-design/pro-chat#85]
### 🥰 需求描述

移动端因为屏幕太小，因此对话气泡和头像在一起很容易出现气泡出现下拉条。

### 🧐 解决方案

是否可以将头像显示作为可选，这一点可以通过气泡的颜色来区分对话对象？
或者将头像放到气泡上面，并且气泡高度可设置，出现下拉条真的难受

**Comment by arvinxx** [comment]
截个图？

**Comment by Bollie15** [comment]
> 截个图？

![image](https://github.com/ant-design/pro-chat/assets/56813612/b59cb286-6dac-4b64-a82e-631c072a43fb)

这里发送icon不见了，是故意设计的吗？

还有一个发送框能不能做到贴底？弹出虚拟键盘时就在上方？现在这个空一大截好变扭

**Comment by arvinxx** [comment]
你自己没加height 100%吧…

**Comment by ONLY-yours** [comment]
@Bollie15  按钮消失是特殊设计的

```tsx
          {mobile ? null : (
            <Button
              loading={ButtonLoading}
              type="text"
              className={styles.btn}
              onClick={() => send()}
              icon={<SendOutlined />}
            />
          )}

```

**Comment by ONLY-yours** [comment]
高度的话设计成为 100vh 或者 100% 应该就好了，默认没有给高度

**Comment by Bollie15** [comment]
看到了，根据文档摸索试出来了
