### ISSUE TITLE
🧐[点击消息发送按钮后，等待消息响应结束，按钮处于加载状态]

### ISSUE THREAD

**Issue by patmosss** [ant-design/pro-chat#86]
### 🧐 问题描述

在点击消息发送按钮后，等待消息响应结束前，按钮处于加载状态。我记得更新前是这样的效果吧？？🤨

### 🚑 其他信息
如官网文档中 [默认的流式输出支持](https://pro-chat.antdigital.dev/guide/why-use-pro-chat#%E9%BB%98%E8%AE%A4%E7%9A%84%E6%B5%81%E5%BC%8F%E8%BE%93%E5%87%BA%E6%94%AF%E6%8C%81)效果图中，所展示。
但是组件文档中的，各个发送按钮并不是这样的效果。

**Comment by ONLY-yours** [comment]
是的，你说的没错，我看下是什么情况导致的问题。

**Comment by ONLY-yours** [comment]
看起来是上次不小心改动导致的，得把单元测试提上日程了，功能先放一下，现在基本完善了

**Comment by ONLY-yours** [comment]
fixed 更新版本即可

**Comment by liguobao** [comment]
感觉没有修正。
