### ISSUE TITLE
🧐[问题]按教程配置后依旧出现Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by johnwick115020115** [ant-design/pro-chat#92]
### 🧐 问题描述

React18+nextjs12，按官方文档配置transpilePackages后，只要一使用Prochat组件就会报错
### 💻 示例代码

使用官方示例的代码没有改动

### 🚑 其他信息

![image](https://github.com/ant-design/pro-chat/assets/137584635/c12caa4f-f623-40ac-a89b-a5fdf8f05538)
![image](https://github.com/ant-design/pro-chat/assets/137584635/c7ca599a-92b6-439e-80fc-2e74bbd0ea3f)
![image](https://github.com/ant-design/pro-chat/assets/137584635/e3916e9c-f94f-4cc3-9036-89607157e5b6)

**Comment by ONLY-yours** [comment]
教程中的是最新 nextjs 14 的版本，nextjs 12 还没试过，我看看哈 @johnwick115020115

**Comment by johnwick115020115** [comment]
> 教程中的是最新 nextjs 14 的版本，nextjs 12 还没试过，我看看哈 @johnwick115020115

感谢，我也试过升级到next14但是一样报错，我对前端也不太熟，没法很好定位问题 :(

**Comment by ONLY-yours** [comment]
个人感觉是老版本的 NextJS 的限制，不允许直接 `import 'reactflow/dist/style.css';`  ，我在新版本的 NextJS 13 和 14 情况下尝试都是ok的。（你可以拉取我们的 [nextjs 14](https://github.com/ant-design/pro-chat/tree/main/demos/chatgpt-nextjs) 的 demo 代码，直接 clone 安装就可以跑起来 ）

还有就是你缺失了一个依赖，antd-styles 安装下，是 ProChat 的底层依赖呢。

```json
 "antd-style": "^3.6.1",
```

具体要修复这个bug 我得先修一下 ProEditor 那边，可能时间会比较久

**Comment by johnwick115020115** [comment]
antd-style这个依赖有的，为了排查错误我给卸载掉了，但是有没有这个依赖都是这个错误，我等下再装一下 。
我也再试一次升级到next14看看有没有问题
@ONLY-yours

**Comment by johnwick115020115** [comment]
我是基于https://github.com/transitive-bullshit/nextjs-notion-starter-kit这个项目开发的，改动的范围很小。
刚才又测试了下，无论是原本的nextjs12还是升级到14，只要在这个项目里引入Prochat使用都会报一样的错误。
@ONLY-yours

**Comment by AmAzing129** [comment]
- 本质是旧版本的 next.js 做了限制：https://github.com/vercel/next.js/issues/19936 因此推荐使用 13 及以上版本，不会存在导入 css 的问题

- 如果必须使用旧版本，注意 transpilePackages 是在 v13 引入的新功能。需要使用插件 https://github.com/martpie/next-transpile-modules 去对依赖包进行转译。需要额外注意的是，使用不同的包管理工具，配置项会不同，请参见文档

- 贴一个我这边使用 pnpm 成功的配置，仅供参考：

```
const withTM = require('next-transpile-modules')(
  [
    '.pnpm/node_modules/@ant-design/pro-editor',
    '@ant-design/pro-chat',
  ]
);
```

- 综上，此问题为 next.js 及 next-transpile-modules 使用问题，非 pro-chat 所致，先关闭了。
