### ISSUE TITLE
🧐[ProChat组件怎么更改聊天框样式啊？]

### ISSUE THREAD

**Issue by Tss-16** [ant-design/pro-chat#96]

**Comment by ONLY-yours** [comment]
@Tss-16 我提供一份文档详细描述下

**Comment by Tss-16** [comment]
> @Tss-16 我提供一份文档详细描述下
ProChat组件里的Input聊天框现在默认是空白block， 怎么更改input框的样式呢？
#

**Comment by ONLY-yours** [comment]
> > @Tss-16 我提供一份文档详细描述下
> > ProChat组件里的Input聊天框现在默认是空白block， 怎么更改input框的样式呢？

如果只是想要修改 Input 的话，有个更简单的 api，inputAreaProps 里面可以穿入 className 来修改即可

**Comment by Tss-16** [comment]
> > > @Tss-16 我提供一份文档详细描述下
> > > ProChat组件里的Input聊天框现在默认是空白block， 怎么更改input框的样式呢？
> 
> 如果只是想要修改 Input 的话，有个更简单的 api，inputAreaProps 里面可以穿入 className 来修改即可

是对话显示的聊天message框不是下方输入的input框

**Comment by Tss-16** [comment]
感谢!!
