### ISSUE TITLE
🐛[BUG]对接流式输出会话内容排版显示异常

### ISSUE THREAD

**Issue by QiMing-Code** [ant-design/pro-chat#99]
### 🐛 bug 描述

流式输出的内容是每次接受到的内容都换行显示了，应该追加显示的，解析markdown格式显示

### 📷 复现步骤

关键部分代码
                const readableStream = new ReadableStream({
                    async start(controller) {
                        function push() {
                            reader
                                .read()
                                .then(({ done, value }: any) => {
                                    if (done) {
                                        controller.close();
                                        return;
                                    }
                                    const decoder = new TextDecoder();
                                    const encoder = new TextEncoder();
                                    const chunk = decoder.decode(value, { stream: true });
                                    const message = chunk.replace('data:', '');
                                    controller.enqueue(encoder.encode(message));
                                    push();
                                })
                                .catch((err: any) => {
                                    console.error('读取流中的数据时发生错误', err);
                                    controller.error(err);
                                });
                        }
                        push();
                    },
                });
                return new Response(readableStream);
![image](https://github.com/ant-design/pro-chat/assets/41195242/597053bf-723a-4a80-8750-0ea600232b3f)

### 🏞 期望结果

![image](https://github.com/ant-design/pro-chat/assets/41195242/26f1d93f-f2a5-4aeb-a91d-085ef0c5cdc8)

### © 版本信息

- @ant-design/pro-chat 版本: [1.9.2]
- 浏览器环境 [谷歌浏览器]
- 开发环境 [mac OS]

**Comment by Tss-16** [comment]
我的ReadableStream返回的一串string支持md文字加粗的显示，但是换行怎么是无效的 有什么办法支持接受的string里支持换行符吗？

**Comment by QiMing-Code** [comment]
通过反复调试看，框架是忠实的现实流式里面的内容，需要用户自行把内容处理成和大模型输出的一样。
我前端是这样处理的：
const message = chunk.replaceAll('data:', '').replace(/(\n|\r)+$/g, '');
去掉流式接口添加的data:和行尾的换行符
服务端是这样推的：
 emitter.send(content, MediaType.TEXT_PLAIN);

**Comment by QiMing-Code** [comment]
> 我的ReadableStream返回的一串string支持md文字加粗的显示，但是换行怎么是无效的 有什么办法支持接受的string里支持换行符吗？

这块需要在流式数据处理那里操作，你把内容打印出来看看有没有丢失换行符
